### ISSUE TITLE
simulation px4 tutorial

### ISSUE THREAD

**Issue by lucasantoro** [wang-chen/uwb_driver#5]
Good evening,
There is a little guide to use your ros package in a simulation in gazebo? I want to use this package to setup a drone (based on px4) in offboard mode, that use 4 ranging to estimate its position.
I'm newby of this world, and is difficult to understand all step that i have to follow.

Thank you very much for your consideration and time

**Comment by wang-chen** [comment]
Hi,
We used the ROS hector_quadrotor package for simulation in gazebo.  You my check the ROS tutorial in the following link. It seems that it only support ROS kinetic currently. 
http://wiki.ros.org/hector_quadrotor
Once you set up the hector_quadrotor package, the UWB gazebo simulation can be run directly.

**Comment by lucasantoro** [comment]
thank you for your answer dear. I'm reading this repo :)
But, with the classical demo of gazebo with iris quadcopter, is possible to use this uwb repo? Because i'm using ros melodic on ubuntu 18.04 LTS

**Comment by wang-chen** [comment]
I just included a header file <random.h> in the file 'uwb_deriver_gazebo.cpp'.
At least on my machine, it has no compelling issue on Ubuntu 18.04 now. 
But I think you need to find how to use hector_quadrotor on Ubuntu 18.04 also.

**Comment by lucasantoro** [comment]
thank you very much. I'm try to understand how to solve this problem, or if there is a way to use with standard example provided by px4 with IRIS quadcopter :)

**Comment by wang-chen** [comment]
Sorry, I am not familiar with this. 😂
